on:
  schedule:
    - cron: "0 5 * * *" # 05:00
    - cron: "0 13 * * *" # 13:00
    - cron: "0 21 * * *" # 21:00
  workflow_dispatch:
name: Get prikdata
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: npm install
      - name: Scrape
        run: npm run action
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
